export default [
    {
        id: 1,
        title: "Brasov",
        location: "Romania",
        googleMapsUrl: "https://goo.gl/maps/guPAa5nm7Cg8x6nt7",
        startDate: "12 September, 2022",
        endDate: "24 September, 2022",
        description: "Brașov is a city in the Transylvania region of Romania, ringed by the Carpathian Mountains. It's known for its medieval Saxon walls and bastions, the towering Gothic-style Black Church and lively cafes.",
        locationIcon: "locationIcon.png",
        imageUrl: "brasov.jpeg",
    },
    {
        id: 2,
        title: "Schwangau",
        location: "Germany",
        googleMapsUrl: "https://goo.gl/maps/zp2TUdyAthBWqVkH8",
        startDate: "20 December, 2017",
        endDate: "22 December, 2017",
        description: "Schwangau is a village in Bavaria, southern Germany. It’s a gateway to the grand Neuschwanstein Castle, a 19th-century hilltop palace built for King Ludwig II.",
        locationIcon: "locationIcon.png",
        imageUrl: "germany.jpeg",
    },
    {
        id: 4,
        title: "Albufeira",
        location: "Portugal",
        googleMapsUrl: "https://goo.gl/maps/TLK8L5pZ11phgTxF7",
        startDate: "1 June, 2022",
        endDate: "5 june, 2022",
        description: "Albufeira is a coastal city in the southern Algarve region of Portugal. It’s a former fishing village that has become a major holiday destination, with sandy beaches and a busy nightlife strip. ",
        locationIcon: "locationIcon.png",
        imageUrl: "portugal.jpeg",
    },
    {
        id: 5,
        title: "Barcelona",
        location: "Spain",
        googleMapsUrl: "https://goo.gl/maps/guPAa5nm7Cg8x6nt7",
        startDate: "15 may, 2019",
        endDate: "20 September, 2019",
        description: "Barcelona, the cosmopolitan capital of Spain’s Catalonia region, is known for its art and architecture. The fantastical Sagrada Família church and other modernist landmarks designed by Antoni Gaudí dot the city. ",
        locationIcon: "locationIcon.png",
        imageUrl: "spain.jpeg",
    }
]